config/routes.rb
BookstoreMaiphan::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root :to => "books#index"
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :categories, only: [:show, :index]

  resources :books, only: [:show, :index] do
    resources :comments, only: [:create]
    collection do
      get :search
    end
  end

  resources :carts, path: 'cart', only: [:index] do
    collection do
      post 'add_book'
      delete 'remove_book'
      put 'update_cart'
    end
  end

  resources :orders, only: [:index, :create, :new]

  

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title, presence: true
  validates :unit_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :total_rating_count, presence: true, numericality: { only_integer:true, greater_than_or_equal_to: 0 }
  validates :total_rating_value, presence: true, numericality: { greater_than_or_equal_to: 0 }

  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :categories

  scope :title_or_author_match, ->(keyword) { where("lower(title) like '%#{keyword.downcase}%' or
                                                     lower(author_name) like '%#{keyword.downcase}%'") }
  scope :of_category, ->(category_id) { joins(:categories).where("categories.id='#{category_id}'") }

  has_attached_file :photo, :styles => { :medium => "200x300>", :thumb => "140x210>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  self.per_page = 12

  def average_rating
    total_rating_count <= 0 ? 0 : (total_rating_value.to_f / total_rating_count).round(2)
  end

  def self.search keyword, category_id, page, per_page
    results = Book.title_or_author_match(keyword)
    results = results.of_category(category_id) if category_id.present?
    results.paginate(page: page, per_page: per_page)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @book = Book.find(params[:id])
    @comments = @book.comments.order(created_at: :desc).paginate(page: params[:page])
    @new_comment = @book.comments.new
  end

  def search
    @books = Book.search params[:query], params[:category], params[:page], params[:per_page]
  end

  def index
    @books = Book.all.paginate(page: params[:page], per_page: params[:per_page])
  end
end

app/views/books/_book.html.haml
%li
  .book-item
    = link_to image_tag(book.photo.url(:thumb)), book_path(book)
    .book-item-title
      = link_to book.title, book_path(book)
    .book-item-author
      = "By: #{book.author_name}"
    .row
      .small-4.columns
        %label.book-price-thumb= number_to_currency(book.unit_price)
      .small-8.columns
        %span.has-tip{title: "Add to cart"}
          = link_to image_tag(image_url('cart.png'), size: "30x30"), add_book_carts_path(book_id: book.id), method: "post"

app/views/books/index.html.haml
.row
  .small-4.medium-3.large-3.columns
    = render partial: 'shared/categories_side_nav'
  .small-8.medium-9.large-9.columns
    .row
      %ul.small-block-grid-1.medium-block-grid-3.large-block-grid-4
        = render @books
    .row
      .medium-4.large-4.columns
        = form_tag books_path, method: :get do
          .row.collapse.left
            .small-5.columns
              %label#per-page-label Books/page
            .small-3.columns
              = number_field_tag :per_page, params[:per_page].present? ? params[:per_page] : Book.per_page, min: 1, id: "per-page-input"
            .small-4.columns
              = submit_tag "Show", class: "postfix", id: "per-page-show-btn"
      .medium-2.large-3.columns
      .medium-6.large-5.columns
        .row.right
          = foundation_paginate @books

app/views/books/search.html.haml
.row
  .small-4.medium-3.large-3.columns
    = render partial: 'shared/categories_side_nav'
  .small-8.medium-9.large-9.columns
    .row
      %h4= "Found #{pluralize(@books.count, 'book')}"
    .row
      %ul.small-block-grid-1.medium-block-grid-3.large-block-grid-4
        = render @books
    - if @books.any?
      .row
        .medium-4.large-4.columns
          = form_tag search_books_path, method: :get do
            = hidden_field_tag :query, params[:query]
            = hidden_field_tag :category, params[:category]
            .row.collapse
              .small-5.columns
                %label#per-page-label Books/page
              .small-3.columns
                = number_field_tag :per_page, params[:per_page].present? ? params[:per_page] : Book.per_page, min: 1, id: "per-page-input"
              .small-4.columns
                = submit_tag "Show", class: "postfix", id: "per-page-show-btn"
        .medium-2.large-3.columns
        .medium-6.large-5.columns
          = foundation_paginate @books

app/views/books/show.html.haml
.book-container
  .row
    .medium-3.large-3.columns
      .book-image= image_tag @book.photo.url(:medium)
    .medium-9.large-9.columns
      %h3.book-title= @book.title
      %h5.book-author= "by #{@book.author_name}"
      .book-avg-rating= "Average rating: #{@book.average_rating}/#{Comment::RATING_VALUES.last} (#{@book.total_rating_count})"
      %p.text-justify.book-description= @book.description
      .row
        .small-6.columns
          .book-publisher= "Publisher: #{@book.publisher_name}"
          .book-publisher= "Published date: #{@book.published_date}"
        .small-6.columns
          .row
            .small-6.columns
              %label.right.book-price= number_to_currency(@book.unit_price)
            .small-6.columns
              %span.has-tip{title: "Add to cart"}
                = link_to image_tag(image_url('cart.png')), add_book_carts_path(book_id: @book.id),
                          method: "post", id: "add-to-cart-btn"
  .row
    .column
      %hr
      - if user_signed_in? && !current_user.commented_on_book?(@book)
        %h4.comment-title Add your comment
        = render "comments/form"
      - else
        - if !user_signed_in?
          .panel Add your comment by signing in.
        - else
          .panel You have rated and commented on this book.

  .row
    .column
      %h4.comment-title= "Comments (#{@comments.count})"
      %ul.no-bullet
        = render @comments
      = foundation_paginate @comments