config/routes.rb
BookstoreMaiphan::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root :to => "books#index"
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :categories, only: [:show, :index]

  resources :books, only: [:show, :index] do
    resources :comments, only: [:create]
    collection do
      get :search
    end
  end

  resources :carts, path: 'cart', only: [:index] do
    collection do
      post 'add_book'
      delete 'remove_book'
      put 'update_cart'
    end
  end

  resources :orders, only: [:index, :create, :new]

  

end

app/models/cart.rb
class Cart
  attr_reader :session

  def initialize(session)
    @session = session
    @session[:cart] ||= {
        books: Hash.new, # Hash{book_id{price, quantity}}
        total_amount: 0,
        created_at: Time.now
    }
  end

  def add_book(book_id)
    requested_book = Book.find_by_id(book_id) if book_id.present?
    if requested_book.present?
      if cart_books[book_id].nil?
        cart_books[book_id] = Hash.new
        cart_books[book_id][:quantity] = 1
      else
        cart_books[book_id][:quantity] += 1
      end
      cart_books[book_id][:total_price] = cart_books[book_id][:quantity] * requested_book.unit_price
      cart[:total_amount] += requested_book.unit_price
      return true
    else
      return false
    end
  end

  def remove_book(book_id)
    requested_book = Book.find_by_id(book_id) if book_id.present?
    if requested_book.present? && cart_books[book_id].present?
      cart[:total_amount] -= cart_books[book_id][:quantity] * requested_book.unit_price
      cart_books.delete(book_id)
    end
  end

  def update_cart(book_ids, quantities)
    book_ids.each_with_index do |book_id, index|
      update_item(book_id, quantities[index])
    end
  end

  def expired?
    cart[:created_at] < 3.hours.ago
  end

  private
    def update_item(book_id, quantity)
      if book_id.present? && quantity.present? && quantity.to_i > 0
        book = Book.find_by_id(book_id) if book_id.present?
        if book.present?
          quantity = quantity.to_i
          quantity_diff = quantity - cart_books[book_id][:quantity]
          cart_books[book_id][:quantity] = quantity
          cart_books[book_id][:total_price] = quantity * book.unit_price
          cart[:total_amount] += quantity_diff * book.unit_price
        end
      end
    end

    def cart
      @session[:cart]
    end

    def cart_books
      @session[:cart][:books]
    end
end

app/models/category.rb
class Category < ActiveRecord::Base
  default_scope { order(:sort_order) }

  validates :name, presence: true
  validates :sort_order, presence: true

  has_and_belongs_to_many :books
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :create_cart

  def index
    @cart_items = session[:cart][:books]
  end

  def update_cart
    if user_signed_in? || !@cart.expired?
      @cart.update_cart(params[:book_ids], params[:quantities])
      redirect_to carts_path
    else
      expire
    end
  end

  def add_book
    if user_signed_in? || !@cart.expired?
      if @cart.add_book(params[:book_id])
        flash[:success] = "Book added succesfully to cart"
        redirect_to carts_path
      else
        flash[:error] = "Book cannot be found"
        redirect_to root_path
      end
    else
      expire
    end
  end

  def remove_book
    if user_signed_in? || !@cart.expired?
      @cart.remove_book(params[:book_id])
      redirect_to carts_path
    else
      expire
    end
  end

  private
    def create_cart
      @cart ||= Cart.new(session)
    end

    def expire
      flash[:alert] = "Your shopping cart has expired!"
      session[:cart] = nil
      @cart = Cart.new(session)
      redirect_to root_path
    end
end

app/views/carts/index.html.haml
.row
  .column
    %h3 Shopping cart
    - if @cart_items.blank?
      No item
    - else
      %ul.button-group.right
        %li= button_to "Continue shopping", books_path, method: :get, class: "button postfix", id: "continue-shopping-btn"
        %li= button_to "Checkout", new_order_path, method: :get, class: "button postfix", id: "checkout-btn"
      = form_tag update_cart_carts_path, method: :put do
        %table#cart-item-table
          %thead.cart-item-head
            %tr
              %td.text-center Title
              %td.text-center Author
              %td.text-center Unit price
              %td.text-center Quantity
              %td.text-center Total price
              %td
          - @cart_items.keys.each do |book_id|
            - cart_item = @cart_items[book_id]
            - book = Book.find_by_id(book_id)
            %tr.cart-item-row
              %td.cart-item-cell= link_to book.title, book_path(book), method: :get
              %td.cart-item-cell= book.author_name
              %td.cart-item-cell.text-right= number_to_currency(book.unit_price)
              %td.cart-item-cell
                = hidden_field_tag "book_ids[]", book_id
                = number_field_tag "quantities[]", cart_item[:quantity], min: 1, class: "cart-item-quantity"
              %td.cart-item-cell.text-right= number_to_currency(cart_item[:total_price])
              %td.cart-item-cell.text-center
                = link_to "Remove", remove_book_carts_path(book_id: book_id), method: :delete, class: "remove-book-link"
          %tr
            %td#total-amount-label Total amount:
            %td{colspan: "4"}
              #total-amount-value.text-right= number_to_currency(session[:cart][:total_amount])
            %td
        .row
          .column
            = submit_tag "Update", class: "button postfix right", id: "update-btn"