config/routes.rb
BookstoreMaiphan::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  root :to => "books#index"
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :categories, only: [:show, :index]

  resources :books, only: [:show, :index] do
    resources :comments, only: [:create]
    collection do
      get :search
    end
  end

  resources :carts, path: 'cart', only: [:index] do
    collection do
      post 'add_book'
      delete 'remove_book'
      put 'update_cart'
    end
  end

  resources :orders, only: [:index, :create, :new]

  

end

app/views/layouts/_header.html.haml
.contain-to-grid.sticky{"data-options" => "sticky_on: large"}
  %nav.top-bar{"data-topbar" => ""}
    %ul.title-area
      %li#top-bar-title
        = link_to "Bookstore.com", root_path
    %section.top-bar-section
      %ul.right
        - if user_signed_in?
          %li= link_to "Cart", carts_path
          %li= link_to "Orders", orders_path
          - if current_user.admin?
            %li= link_to "Admin", rails_admin_path
          %li.has-dropdown
            = link_to current_user.full_name, '#', id: "user-name"
            %ul.dropdown
              %li= link_to 'Edit profile', edit_user_registration_path
              %li= link_to "Sign out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Sign in", new_user_session_path
          %li= link_to "Sign up", new_user_registration_path

.panel#search-bar
  .row
    = form_tag search_books_path, method: :get do
      .row.collapse.right
        .small-4.columns
          = select_tag :category, options_for_select(@categories)
        .small-5.columns
          = text_field_tag :query, params[:query], placeholder: "Title/Author name"
        .small-3.columns
          = submit_tag "Search", class: "button postfix"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "Bookstore" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="container">
    <%= render 'layouts/header' %>
    <div class="row">
      <% flash.each do |key, value| %>
        <div class="alert-box <%= key %> radius"><%= value %></div>
      <% end %>
    </div>
    <div>
        <%= yield %>
    </div>
  </div>
<%= javascript_include_tag "application" %>
</body>
</html>